### ISSUE TITLE
Not able to run the Complete part 

### ISSUE THREAD

**Issue by sohambannerjee8** [spring-guides/gs-messaging-rabbitmq#5]
Here is my  errors

```
Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'exclude' is of type [Class[]], but [String[]] was expected. Cause: 
	at org.springframework.core.annotation.AnnotationAttributes.doGet(AnnotationAttributes.java:117)
	at org.springframework.core.annotation.AnnotationAttributes.getStringArray(AnnotationAttributes.java:70)
	at org.springframework.boot.autoconfigure.EnableAutoConfigurationImportSelector.selectImports(EnableAutoConfigurationImportSelector.java:63)
	at org.springframework.context.annotation.ConfigurationClassParser.processImport(ConfigurationClassParser.java:386)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:204)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:163)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:138)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:284)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:225)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:630)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:683)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:944)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:933)
	at Application.main(Application.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Here is the link on the stackoverflow

http://stackoverflow.com/questions/29892408/whats-wrong-with-rabbitmq-in-spring-boot

**Comment by artembilan** [comment]
Looks like the project hasn't been properly imported to the IDEA.
Try to import it as Gradle project, or install Maven and do the same for pom.

**Comment by artembilan** [comment]
Just have done the same importing as Maven project and works well again.

**Comment by sohambannerjee8** [comment]
Ok you are right.I have solved the problem.I have created another new project any reimport everything and it's running
.Sorry for the trouble.
