### ISSUE TITLE
Problem with building sample rabbitmq code in gradle

### ISSUE THREAD

**Issue by scheung38** [spring-guides/gs-messaging-rabbitmq#9]
After launching rabbitmq-server and then ran the sample code in gradle, but sure why cannot build :

https://bitbucket.org/niceseb/myrabbitmq

```
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
        at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:75)
        at org.springframework.boot.gradle.run.BootRunTask.exec(BootRunTask.java:63)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more


BUILD FAILED
```

**Comment by artembilan** [comment]
Sorry for delay and misunderstanding your issue, but it fully isn't clear what you're doing wrong.
My logs looks like:
```
:clean
:compileJava
:processResources
:classes
:findMainClass
:bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.1.RELEASE)

2015-12-28 15:28:52.115  INFO 5172 --- [           main] hello.Application                        : Starting Application on HOME with PID 5172 (D:\SpringIO\gs-messaging-rabbitmq\complete\build\classes\main started by abilan in D:\SpringIO\gs-messaging-rabbitmq\complete)
2015-12-28 15:28:52.117  INFO 5172 --- [           main] hello.Application                        : No active profile set, falling back to default profiles: default
2015-12-28 15:28:52.150  INFO 5172 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@64485a47: startup date [Mon Dec 28 15:28:52 EST 2015]; root of context hierarchy
2015-12-28 15:28:52.645  INFO 5172 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.amqp.rabbit.annotation.RabbitBootstrapConfiguration' of type [class org.springframework.amqp.rabbit.annotation.RabbitBootstrapConfiguration$$EnhancerBySpringCGLIB$$f56c92e7] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2015-12-28 15:28:53.040  INFO 5172 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-12-28 15:28:53.044  INFO 5172 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
2015-12-28 15:28:53.087  INFO 5172 --- [cTaskExecutor-1] o.s.a.r.c.CachingConnectionFactory       : Created new connection: SimpleConnection@5e1b6448 [delegate=amqp://guest@127.0.0.1:5672/]
2015-12-28 15:28:53.088  INFO 5172 --- [cTaskExecutor-1] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (spring-boot) durable:false, auto-delete:false, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
Waiting five seconds...
Sending message...
Received <Hello from RabbitMQ!>
2015-12-28 15:28:58.122  INFO 5172 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@64485a47: startup date [Mon Dec 28 15:28:52 EST 2015]; root of context hierarchy
2015-12-28 15:28:58.124  INFO 5172 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2015-12-28 15:28:58.128  INFO 5172 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2015-12-28 15:28:59.125  INFO 5172 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2015-12-28 15:28:59.126  INFO 5172 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2015-12-28 15:28:59.129  INFO 5172 --- [           main] hello.Application                        : Started Application in 7.198 seconds (JVM running for 7.439)

BUILD SUCCESSFUL

Total time: 12.623 secs
```
and this is after running `gradlew clean bootRun` from the `gs-messaging-rabbitmq\complete` directory.

I'm not sure how your own project is related to this Guide, but check your project with the same Gradle version, not 2.9: https://bitbucket.org/niceseb/myrabbitmq/src/c77a8eff3b596918b89f86c34b038962f40b86fa/build.gradle?at=master&fileviewer=file-view-default#build.gradle-53

**Comment by gregturn** [comment]
Can you include what you typed with the output?

**Comment by gregturn** [comment]
Seeing no follow up I'm closing this issue.
